### ISSUE TITLE
ghidra link is broken

### ISSUE THREAD

**Issue by brootware** [archcloudlabs/kali-up#15]
New download link is via GitHub:
https://github.com/NationalSecurityAgency/ghidra/releases/tag/Ghidra_10.1.1_build

Will have to modify this and do a PR.

**Comment by brootware** [comment]
Seems like we're able to install ghidra directly from apt module instead of downloading from GitHub in latest version of kali.

**Comment by brootware** [comment]
Following up on this, I've kept the installation steps for all the tools the same inclusive of ghidra. 
- Identified a few roles that are broken. 
- Fixed and refactored the roles for easier development. 

More details can be found in [v2 release](https://github.com/brootware/kali-up/releases).
Going forward, I would suggest keeping this repo the same only with provisioning the roles locally and with VirtualBox. Please lemme know your thoughts. @archcloudlabs

**Comment by archcloudlabs** [comment]
Fixed!
